const $ = (id) => document.getElementById(id);
const saveItemButton = document.querySelector('#itemForm button[type="submit"]');
let items = [], selected = new Set(), refreshTimer, editorImages = [], removedImageIds = [];
const money = (v) => `₹${Number(v).toLocaleString('en-IN', {maximumFractionDigits:2})}`;
const unitText = (u) => ({piece:'piece',kg:'kg',gram:'100 g',litre:'litre',packet:'packet',dozen:'dozen'}[u] || u);
const token = () => sessionStorage.getItem('pricepocket-token');
const escapeHtml = (text) => { const e = document.createElement('span'); e.textContent = text; return e.innerHTML; };
function toast(message) { $('toast').textContent = message; $('toast').classList.add('show'); setTimeout(() => $('toast').classList.remove('show'), 2400); }
async function api(path, options = {}) {
  const response = await fetch(`/.netlify/functions${path}`, {...options, headers:{'Content-Type':'application/json', ...(token()?{Authorization:`Bearer ${token()}`}:{}) ,...options.headers}});
  if (response.status === 401) { sessionStorage.removeItem('pricepocket-token'); showLogin(); throw new Error('Session expired'); }
  if (!response.ok) throw new Error((await response.json().catch(()=>({}))).error || 'Request failed');
  return response.status === 204 ? null : response.json();
}
function render() {
  const query = $('search').value.trim().toLowerCase(), filtered = items.filter(item => item.name.toLowerCase().includes(query));
  $('items').innerHTML = filtered.map(item => `<article class="item-row ${selected.has(item.id)?'selected':''}"><input class="select-dot" type="checkbox" data-select="${item.id}" ${selected.has(item.id)?'checked':''} aria-label="Select ${escapeHtml(item.name)}">${item.images?.[0]?.signedUrl ? `<img class="item-thumb" src="${item.images[0].signedUrl}" alt="">` : ''}<div class="item-main"><h3 class="item-name">${escapeHtml(item.name)}</h3><div class="history-list">${item.history.slice(0,3).map(price => `<span class="history-price">${money(price)}</span>`).join('')}</div></div><div class="row-price"><div class="price">${money(item.history[0])}</div><div class="unit">per ${escapeHtml(unitText(item.unit))}</div></div><div class="row-actions"><button class="mini-action" data-edit="${item.id}">Edit</button><button class="mini-action delete" data-delete="${item.id}">×</button></div></article>`).join('');
  $('emptyState').hidden = Boolean(filtered.length); $('itemSummary').textContent = `${items.length} item${items.length===1?'':'s'} in your shop`; $('selectionCount').textContent = selected.size; $('shareSelected').classList.toggle('has-selection', Boolean(selected.size)); $('clearSelection').hidden = !selected.size;
}
async function loadItems(silent=false) { try { items = await api('/items'); render(); } catch { if (!silent && token()) toast('Unable to load prices'); } }
function showLogin() { clearInterval(refreshTimer); $('loginScreen').hidden=false; $('appShell').hidden=true; $('addItem').hidden=true; }
function showApp() { $('loginScreen').hidden=true; $('appShell').hidden=false; $('addItem').hidden=false; loadItems(); clearInterval(refreshTimer); refreshTimer=setInterval(()=>loadItems(true),10000); }
function renderImagePreview() { $('imagePreview').innerHTML = editorImages.map((image,index) => `<div class="preview-card"><img src="${image.signedUrl || image.previewUrl}" alt="Item preview"><button type="button" class="remove-image" data-remove-image="${index}" aria-label="Remove image">×</button></div>`).join(''); }
function setUnit(unit) { const fixed = ['piece','kg','gram','litre','packet','dozen']; $('unit').value = fixed.includes(unit) ? unit : 'custom'; $('customUnitWrap').hidden = fixed.includes(unit); $('customUnit').value = fixed.includes(unit) ? '' : (unit || ''); }
function openEditor(item) { $('itemForm').reset(); $('editingId').value=item?.id||''; $('editorTitle').textContent=item?'Edit item':'Add an item'; $('name').value=item?.name||''; $('price').value=item?.history[0]??''; setUnit(item?.unit||'piece'); editorImages = [...(item?.images||[])]; removedImageIds=[]; renderImagePreview(); $('backdrop').hidden=$('editor').hidden=false; setTimeout(()=>$('name').focus(),50); }
function closeEditor() { $('backdrop').hidden=$('editor').hidden=true; }
function customUnit() { return $('unit').value === 'custom' ? $('customUnit').value.trim() : $('unit').value; }
async function uploadImage(file) {
  if (!file || typeof file !== 'object') throw new Error('Please select an image first');
  const auth = await api('/imagekit-auth'); const safeName = file.name.replace(/[^a-z0-9._-]/gi,'-'); const body = new FormData();
  body.append('file',file); body.append('fileName',`${crypto.randomUUID()}-${safeName}`); body.append('folder','/pricepocket'); body.append('useUniqueFileName','true'); body.append('isPrivateFile','true'); body.append('publicKey',auth.publicKey); body.append('signature',auth.signature); body.append('expire',auth.expire); body.append('token',auth.token);
  const response = await fetch('https://upload.imagekit.io/api/v1/files/upload',{method:'POST',body}); const image = await response.json().catch(()=>({})); if (!response.ok) throw new Error(image.message || image.error || 'ImageKit upload failed'); return {fileId:image.fileId,filePath:image.filePath,name:image.name,url:image.url};
}
$('loginForm').onsubmit=async event=>{ event.preventDefault(); $('loginError').textContent=''; $('loginButton').disabled=true; try { const result=await api('/auth-login',{method:'POST',body:JSON.stringify({email:$('email').value.trim(),password:$('password').value})}); sessionStorage.setItem('pricepocket-token',result.token); showApp(); } catch { $('loginError').textContent='Incorrect email or password.'; } finally { $('loginButton').disabled=false; } };
$('signOut').onclick=()=>{sessionStorage.removeItem('pricepocket-token');showLogin();}; $('addItem').onclick=()=>openEditor(); $('closeEditor').onclick=closeEditor; $('backdrop').onclick=closeEditor; $('search').oninput=render; $('clearSelection').onclick=()=>{selected.clear();render();};
$('unit').onchange=()=>{ $('customUnitWrap').hidden=$('unit').value!=='custom'; if ($('unit').value==='custom') $('customUnit').focus(); };
$('images').onchange=event=>{ const incoming=[...event.target.files]; if (editorImages.length+incoming.length>3) { toast('You can add up to 3 photos only'); event.target.value=''; return; } editorImages.push(...incoming.map(file=>({file,previewUrl:URL.createObjectURL(file)}))); event.target.value=''; renderImagePreview(); };
$('imagePreview').onclick=event=>{ const index=event.target.dataset.removeImage; if (index===undefined) return; const [removed]=editorImages.splice(Number(index),1); if (removed.fileId) removedImageIds.push(removed.fileId); renderImagePreview(); };
$('itemForm').onsubmit=async event=>{ event.preventDefault(); const id=$('editingId').value, name=$('name').value.trim(), price=Number($('price').value), unit=customUnit(), old=items.find(item=>item.id===id); if (!unit) return toast('Enter a custom unit'); const history=old?(old.history[0]===price?old.history:[price,...old.history].slice(0,3)):[price]; try { saveItemButton.disabled=true; const newFiles=editorImages.filter(image=>image.file); const uploaded=await Promise.all(newFiles.map(uploadImage)); const existing=editorImages.filter(image=>!image.file).map(({fileId,filePath,name,url})=>({fileId,filePath,name,url})); const images=[...existing,...uploaded]; await api(id?`/items?id=${encodeURIComponent(id)}`:'/items',{method:id?'PUT':'POST',body:JSON.stringify({name,unit,history,images,removedImageIds})}); closeEditor(); await loadItems(); toast(old?'Item updated for everyone':'Item added for everyone'); } catch(error) { toast(error.message||'Could not save item'); } finally { saveItemButton.disabled=false; } };
$('items').onclick=async event=>{ const id=event.target.dataset.edit||event.target.dataset.delete||event.target.dataset.select; if(!id)return; const item=items.find(entry=>entry.id===id); if(event.target.dataset.select){selected.has(id)?selected.delete(id):selected.add(id);render();} else if(event.target.dataset.edit)openEditor(item); else if(event.target.dataset.delete&&confirm(`Delete ${item.name}?`)){try{await api(`/items?id=${encodeURIComponent(id)}`,{method:'DELETE'});selected.delete(id);await loadItems();toast('Item deleted for everyone');}catch{toast('Could not delete item');}} };
$('shareSelected').onclick=async()=>{ const chosen=items.filter(item=>selected.has(item.id)); if(!chosen.length)return toast('Select items to share first'); const shareButton=$('shareSelected'); try { shareButton.classList.add('share-loading'); const imageFiles=[]; for(const item of chosen) for(const image of item.images||[]) { const response=await fetch(image.signedUrl); if(!response.ok) throw new Error(); const blob=await response.blob(); imageFiles.push(new File([blob],image.name||'product-photo.jpg',{type:blob.type||'image/jpeg'})); } const text=`Adash Silai Materials — selected products and current prices.\n\n${chosen.map(item=>`• ${item.name}: ${money(item.history[0])} per ${unitText(item.unit)}`).join('\n')}`; if(imageFiles.length && navigator.canShare?.({files:imageFiles})) await navigator.share({title:'Adash Silai Materials',text,files:imageFiles}); else if(navigator.share) { await navigator.share({title:'Adash Silai Materials',text}); toast('Details shared without images.'); } else { await navigator.clipboard.writeText(text); toast('Details copied without images.'); } } catch(error) { if(error.name!=='AbortError') toast('Could not prepare photos for sharing'); } finally { shareButton.classList.remove('share-loading'); } };
token()?showApp():showLogin();
